apiVersion: v1
entries:
  task-5-mysql:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-11-11T00:39:01.269902987+05:00"
    description: A Helm chart for Kubernetes
    digest: 6ec904991c81b7dbd1a20d959a76515418f11e536e335141958f6f950d188736
    name: task-5-mysql
    type: application
    urls:
    - https://askhat-zab.github.io/repo/helm/charts/task-5-mysql-0.1.0.tgz
    version: 0.1.0
  task-5-wordpress:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-11-11T00:39:01.270263228+05:00"
    description: A Helm chart for Kubernetes
    digest: 9a7e581f6a922474dceb799acfb34267a909075065317a94faf0fb6717071b89
    name: task-5-wordpress
    type: application
    urls:
    - https://askhat-zab.github.io/repo/helm/charts/task-5-wordpress-0.1.0.tgz
    version: 0.1.0
generated: "2024-11-11T00:39:01.269415503+05:00"
