apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "task-5-mysql.fullname" . }}-configmap
  labels:
{{ include "task-5-mysql.labels" . | indent 4 }}
data:
{{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
